services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    CookieBundle\EventListener\Html:
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse, priority: -150 }
